name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout files in repo
      uses: actions/checkout@master
    
    - name: try-local-build
      uses: ./
      with:
        argo_url: ${{ secrets.ARGO_URI }}
        application_credentials: ${{ secrets.APPLICATION_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}
        location_zone: ${{ secrets.LOCATION_ZONE }}
        cluster_name: ${{ secrets.CLUSTER_NAME }}
        workflow_yaml_path: "examples/coinflip.yaml"
        parameter_file_path: "examples/arguments-parameters.yaml"

    - name: Prebuild Image
      run: |
        cd $GITHUB_WORKSPACE
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
        docker build -t geewynn/gke-k8s -f prebuild.Dockerfile .
        docker push geewynn/gke-k8s
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: pull from Docker
      id: argo
      uses: ml-projects-cicd/argo-k8s@main
      with:
        argo_url: ${{ secrets.ARGO_URI }}
        application_credentials: ${{ secrets.APPLICATION_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}
        location_zone: ${{ secrets.LOCATION_ZONE }}
        cluster_name: ${{ secrets.CLUSTER_NAME }}
        workflow_yaml_path: "examples/coinflip.yaml"
        parameter_file_path: "examples/arguments-parameters.yaml"
    
    - name: test argo outputs
      run: echo "Argo URL $WORKFLOW_URL"
      env:
        WORKFLOW_URL: ${{ steps.argo.outputs.WORKFLOW_URL }}
